export const CURRENT_USER_FETCH_REQUEST = 'CURRENT_USER_FETCH_REQUEST';
export const CURRENT_USER_FETCH_SUCCESS = 'CURRENT_USER_FETCH_SUCCESS';
export const CURRENT_USER_FETCH_ERROR = 'CURRENT_USER_FETCH_ERROR';

export const LOADER_SHOW = 'LOADER_SHOW';
export const LOADER_HIDE = 'LOADER_HIDE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const SET_ACTIVE_GROUP = 'SET_ACTIVE_GROUP';
export const FILMS_FETCH = 'FILMS_FETCH';
export const FILMS_ERROR = 'FILMS_ERROR';
export const FILMS_SUCCESS = 'FILMS_SUCCESS';